// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7KwsL-mZ54IPZVytG5bi7_cxR5cQSnA4',
    appId: '1:20794466737:web:56ce1240f96ae8c90a1d90',
    messagingSenderId: '20794466737',
    projectId: 'studentappfirebase-eceea',
    authDomain: 'studentappfirebase-eceea.firebaseapp.com',
    storageBucket: 'studentappfirebase-eceea.appspot.com',
    measurementId: 'G-4YZ11QLE8X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLNVccVvhZLZD9RXN_2JmP0WDtQZCmXX8',
    appId: '1:20794466737:android:6e65b42b4ba9168e0a1d90',
    messagingSenderId: '20794466737',
    projectId: 'studentappfirebase-eceea',
    storageBucket: 'studentappfirebase-eceea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4PMefbUXN9NRiVBfVpMOGkI0ntgFVBQE',
    appId: '1:20794466737:ios:b68defd380299b6a0a1d90',
    messagingSenderId: '20794466737',
    projectId: 'studentappfirebase-eceea',
    storageBucket: 'studentappfirebase-eceea.appspot.com',
    iosBundleId: 'com.example.studentappFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4PMefbUXN9NRiVBfVpMOGkI0ntgFVBQE',
    appId: '1:20794466737:ios:b68defd380299b6a0a1d90',
    messagingSenderId: '20794466737',
    projectId: 'studentappfirebase-eceea',
    storageBucket: 'studentappfirebase-eceea.appspot.com',
    iosBundleId: 'com.example.studentappFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7KwsL-mZ54IPZVytG5bi7_cxR5cQSnA4',
    appId: '1:20794466737:web:44f147460f8d76b20a1d90',
    messagingSenderId: '20794466737',
    projectId: 'studentappfirebase-eceea',
    authDomain: 'studentappfirebase-eceea.firebaseapp.com',
    storageBucket: 'studentappfirebase-eceea.appspot.com',
    measurementId: 'G-1NFGYM7YHD',
  );
}
