// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKzoIiwskKS7vWenihbCaRznFwRiVzvJ4',
    appId: '1:809645972266:web:17f47404c72e2c1ec99c53',
    messagingSenderId: '809645972266',
    projectId: 'student-b3fab',
    authDomain: 'student-b3fab.firebaseapp.com',
    storageBucket: 'student-b3fab.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa3svU8VJBCAa-RgWeE-X9nLjGOkHwoKk',
    appId: '1:809645972266:android:0a9c8cd4b0fb23ecc99c53',
    messagingSenderId: '809645972266',
    projectId: 'student-b3fab',
    storageBucket: 'student-b3fab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWhA5h2Ul-jBkYTIXZKatH44AdhUKyzl0',
    appId: '1:809645972266:ios:77e4e3701230cd90c99c53',
    messagingSenderId: '809645972266',
    projectId: 'student-b3fab',
    storageBucket: 'student-b3fab.appspot.com',
    iosBundleId: 'com.example.studentappFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWhA5h2Ul-jBkYTIXZKatH44AdhUKyzl0',
    appId: '1:809645972266:ios:77e4e3701230cd90c99c53',
    messagingSenderId: '809645972266',
    projectId: 'student-b3fab',
    storageBucket: 'student-b3fab.appspot.com',
    iosBundleId: 'com.example.studentappFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKzoIiwskKS7vWenihbCaRznFwRiVzvJ4',
    appId: '1:809645972266:web:491818932330cc03c99c53',
    messagingSenderId: '809645972266',
    projectId: 'student-b3fab',
    authDomain: 'student-b3fab.firebaseapp.com',
    storageBucket: 'student-b3fab.appspot.com',
  );

}